app:
  name: "web_app"
  mode: "dev"
  port: 8088

log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql :
  host: "localhost"
  port: 13306
  user: root
  password: root
  dbname: "sql_demo"
  max_open_conns: 200
  max_idle_conns: 50

redis:
  host: "localhost"
  prot: 6379
  db: 0
  password: ""
  pool_size: 100